### ISSUE TITLE
Core dumped / segmentation fault

### ISSUE THREAD

**Issue by lysa324** [amaiya/onprem#41] opened 2023-11-03 12:19 UTC
Hi, 
I use debian 11,
python 3.10, 
anaconda3
onprem==0.0.28
langchain==0.0.240
RAM = 16 Go
swap = 10 Go
SSD = 60 GO
I try to use the simplest program with onprem : 

```
from onprem import LLM
llm = LLM()

prompt = """Extract the names of people in the supplied sentences. Here is an example:
Sentence: James Gandolfini and Paul Newman were great actors.
People:
James Gandolfini, Paul Newman
Sentence:
I like Cillian Murphy's acting. Florence Pugh is great, too.
People:"""
saved_output = llm.prompt(prompt)

```
and i have "core dumped " error without other details, i tried a lot of things but nothig resolve my problem ! 

can you help me please 
thks

**Comment by amaiya** [comment] 2023-11-17 23:12
It's difficult to pinpoint your issue without more information.  I will close this issue for now, since it cannot be reproduced.  Feel free to respond to this thread.

**Closed by amaiya** 2023-11-17 23:12 UTC
